"""第一次迁移

Revision ID: ad2b77ddf892
Revises: 
Create Date: 2020-02-08 12:13:40.457444

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ad2b77ddf892'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book', 'isbn',
               existing_type=mysql.VARCHAR(length=15),
               nullable=False)
    op.alter_column('book', 'title',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.create_unique_constraint(None, 'book', ['isbn'])
    op.drop_column('user', 'beans')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('beans', mysql.FLOAT(), nullable=True))
    op.drop_constraint(None, 'book', type_='unique')
    op.alter_column('book', 'title',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('book', 'isbn',
               existing_type=mysql.VARCHAR(length=15),
               nullable=True)
    # ### end Alembic commands ###
